apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  AUTH_TITLE: {{ .Values.config.AUTH_TITLE | quote }}
  AUTH_WELCOME: {{ .Values.config.AUTH_WELCOME | quote }}
  AUTH_FOOTER: {{ .Values.config.AUTH_FOOTER | default "© 2024" | quote }}
  PROFILE_TITLE: {{ .Values.config.PROFILE_TITLE | quote }}
  PROFILE_MESSAGE: {{ .Values.config.PROFILE_MESSAGE | quote }}
  NOTIFY_TITLE: {{ .Values.config.NOTIFY_TITLE | quote }}
  NOTIFY_MESSAGE: {{ .Values.config.NOTIFY_MESSAGE | quote }}
  PROFILE_SERVICE_URL: {{ .Values.config.PROFILE_SERVICE_URL | quote }}
  NOTIFICATION_SERVICE_URL: {{ .Values.config.NOTIFICATION_SERVICE_URL | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | default "INFO" | quote }}
  # HTML страницы
  auth_html: {{ .Values.config.auth_html | quote }}
  profile_html: {{ .Values.config.profile_html | quote }}
  notify_html: {{ .Values.config.notify_html | quote }}