# f1-app-chart/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.db.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.db.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.secrets.db.POSTGRES_DB }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.auth.JWT_SECRET }}
  API_KEY: {{ .Values.secrets.auth.API_KEY }}