apiVersion: v1
kind: Service
metadata:
  name: f1-app-auth-service
  namespace: exam-yacenko
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: f1-app
    meta.helm.sh/release-namespace: exam-yacenko
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30007